/* Regression checks for counters, saved profiles, pauses, undo, and offline UI. */
const assert = require('node:assert/strict');
const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('playwright');
const html = fs.readFileSync(path.join(__dirname, '../src/index.html'));
const server = http.createServer((req, res) => { res.setHeader('Content-Type', 'text/html; charset=utf-8'); res.end(html); });
let browser, checks = 0;
const check = (condition, description) => { assert(condition, description); checks++; console.log('PASS ' + description); };
const value = (page,id) => page.locator('#'+id).textContent();
const row = (page,name) => page.locator('.item-row').filter({has:page.locator('.item-name',{hasText:new RegExp('^'+name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'$')})});
async function answer(page, text, extra) {
  const dialog=page.locator('#actionDialog'); await dialog.waitFor({state:'visible'});
  if(text!==null) await dialog.locator('input:not([type=checkbox])').fill(String(text));
  if(extra) await dialog.locator('input[type=checkbox]').check();
  await dialog.locator('#dialogConfirm').click(); await dialog.waitFor({state:'hidden'});
}
async function session(url, options={}) {
  const context=await browser.newContext({viewport:{width:1100,height:950},timezoneId:'Europe/Berlin',...options});
  const errors=[],external=[];
  context.on('page',page=>page.on('pageerror',e=>errors.push(e.message)));
  await context.route('**/*',route=>{if(route.request().url().startsWith(url))return route.continue();external.push(route.request().url());return route.abort();});
  const page=await context.newPage();return {context,page,errors,external};
}
(async()=>{
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  const url='http://127.0.0.1:'+server.address().port;
  browser=await chromium.launch({headless:true,args:['--no-sandbox',...(process.env.COUNTER_TEST_SINGLE_PROCESS?['--single-process','--no-zygote','--disable-gpu']:[])],...(process.env.COUNTER_BROWSER?{executablePath:process.env.COUNTER_BROWSER}:{})});
  const {context,page,errors,external}=await session(url);
  await page.goto(url); await page.locator('.item-row').first().waitFor();
  check(await page.locator('.item-row').count()===8,'eight original categories');
  for(let i=0;i<3;i++)await row(page,'НДЗ').locator('[data-action=plus]').click();
  for(let i=0;i<2;i++)await row(page,'Успешно').locator('[data-action=plus]').click();
  for(let i=0;i<4;i++)await page.locator('#commPlus').click();
  check(await value(page,'totalComm')==='5'&&await value(page,'commCount')==='4','category total and independent communications');
  check(await value(page,'effSuccess')==='40%','success ratio uses category total');
  await row(page,'Успешно').locator('[data-action=menu]').click();await page.locator('#itemEditBtn').click(); await answer(page,7);
  check(await value(page,'totalComm')==='10','manual category edits adjust total');
  await page.locator('#undoBtn').click();
  await row(page,'Успешно').locator('[data-action=plus]').click();
  await page.locator('#undoBtn').click(); await page.locator('#undoBtn').click();
  check(await value(page,'totalComm')==='5'&&await value(page,'commCount')==='3','undo snapshots survive subsequent mutations');
  await page.locator('#settingsBtn').click();await page.locator('#profileAddBtn').click(); await page.keyboard.press('Escape');await page.locator('#actionDialog').waitFor({state:'hidden'});
  check(await page.locator('#profileSelect option').count()===1,'cancelled new-profile dialog changes nothing');
  await page.locator('#settingsBtn').click();await page.locator('#profileAddBtn').click(); await answer(page,'Кира');
  await row(page,'VIP').locator('[data-action=plus]').click();
  await page.locator('#settingsBtn').click();await page.locator('#profileRenameBtn').click();await answer(page,'Кира V2');
  await page.reload();
  check(await page.locator('#profileSelect').inputValue()==='Кира V2'&&await value(page,'totalComm')==='1','profile rename and selected profile persist');
  await page.locator('#profileSelect').selectOption('default');
  check(await value(page,'totalComm')==='5'&&await value(page,'commCount')==='3','profile switching restores independent data');
  const dangerous='<img src=x onerror=alert(1)>';
  await page.locator('#addBtn').click();await answer(page,dangerous);
  check(await row(page,dangerous).count()===1&&await page.locator('#itemsContainer img').count()===0,'category labels are rendered as text');
  await page.locator('#addBtn').click();await answer(page,'__proto__');
  await row(page,'__proto__').locator('[data-action=plus]').click();
  check(await value(page,'totalComm')==='6','prototype-like category names work safely');
  await page.clock.setFixedTime(new Date('2026-10-06T07:00:00Z'));
  await page.locator('#startShiftBtn').click();
  await page.clock.setFixedTime(new Date('2026-10-06T07:30:00Z'));await page.locator('#pauseShiftBtn').click();
  await page.clock.setFixedTime(new Date('2026-10-06T07:50:00Z'));await page.reload();await page.waitForTimeout(30);
  check(await value(page,'shiftTimerValue')==='00:30:00'&&await value(page,'shiftStatusText')==='Пауза','pause remains frozen after restart');
  await page.clock.setFixedTime(new Date('2026-10-06T08:00:00Z'));await page.locator('#pauseShiftBtn').click();
  await page.clock.setFixedTime(new Date('2026-10-06T08:15:00Z'));await page.waitForTimeout(1050);
  check(await value(page,'shiftTimerValue')==='00:45:00','resumed shift excludes all paused time');
  await page.locator('#shiftNotes').fill('<b>Заметка</b>');
  await page.locator('#endShiftBtn').click();await answer(page,null);await page.locator('#historyBtn').click();
  check(await page.locator('.history-item').count()===1&&await page.locator('#historyList b').count()===0,'completed shift is archived without HTML injection');
  await page.locator('#historyCloseBtn').click();await page.locator('#historyDialog').waitFor({state:'hidden'});
  await page.locator('#resetBtn').click();await answer(page,null,true);
  check(await value(page,'totalComm')==='0'&&await value(page,'shiftStatusText')==='Не начата','reset can include shift state');
  await page.locator('#undoBtn').click();
  check(await value(page,'totalComm')==='6'&&await value(page,'shiftStatusText')==='Завершена','reset is reversible');
  await page.clock.setFixedTime(new Date('2026-10-06T21:00:00Z'));await page.locator('#startShiftBtn').click();
  await page.locator('#shiftEnd').fill('07:00');await page.locator('#shiftEnd').blur();await page.waitForTimeout(1050);
  check(await value(page,'shiftStatusText')==='Идёт','overnight schedule does not end before midnight');
  await page.clock.setFixedTime(new Date('2026-10-07T05:00:00Z'));await page.waitForTimeout(1050);
  check(await value(page,'shiftStatusText')==='Завершена','overnight schedule ends on next day');
  await page.locator('#themeToggle').click();await page.reload();
  check(await page.locator('html').getAttribute('data-theme')==='dark','theme selection survives restart');
  const downloadPromise=page.waitForEvent('download');await page.locator('#exportCsvBtn').click();const download=await downloadPromise;
  const stream=await download.createReadStream(),parts=[];for await(const part of stream)parts.push(part);const csv=Buffer.concat(parts).toString('utf8');
  check(csv.startsWith('\uFEFF')&&csv.includes('"__proto__","1"'),'CSV exports UTF-8 and current values');
  // Keyboard focus is retained because counter rows are not recreated on each click.
  const plus=row(page,'НДЗ').locator('[data-action=plus]');await plus.focus();await page.keyboard.press('Enter');await page.keyboard.press('Enter');
  check(await plus.evaluate(el=>document.activeElement===el),'keyboard focus survives repeated increments');
  check(errors.length===0,'no JavaScript errors');check(external.length===0,'no network resources or CDN dependencies');
  await context.close();
  if(process.env.COUNTER_TEST_SINGLE_PROCESS){await browser.close();browser=await chromium.launch({headless:true,args:['--no-sandbox','--single-process','--no-zygote','--disable-gpu'],executablePath:process.env.COUNTER_BROWSER});}
  const legacy=await session(url,{reducedMotion:'reduce',viewport:{width:390,height:844}});
  await legacy.page.addInitScript(()=>{if(!localStorage.getItem('seeded')){localStorage.setItem('seeded','1');localStorage.setItem('commStatsData',JSON.stringify({itemOrder:['НДЗ','Успешно'],counts:{НДЗ:9,Успешно:4},totalCount:13,commCount:6,shiftStart:'09:00',shiftEnd:'18:00'}));}});
  await legacy.page.goto(url);
  check(await value(legacy.page,'totalComm')==='13'&&await value(legacy.page,'commCount')==='6','legacy single-profile data is migrated');
  check(await legacy.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'compact layout has no horizontal scroll');
  await legacy.page.locator('#commPlus').click();
  check(await legacy.page.locator('.ripple').count()===0,'reduced-motion preference suppresses effects');
  await legacy.context.close();
  if(process.env.COUNTER_TEST_SINGLE_PROCESS){await browser.close();browser=await chromium.launch({headless:true,args:['--no-sandbox','--single-process','--no-zygote','--disable-gpu'],executablePath:process.env.COUNTER_BROWSER});}
  const native=await session(url);
  await native.page.addInitScript(()=>{window.chrome??={};window.chrome.webview={postMessage:m=>(window.nativeMessages??=[]).push(m),addEventListener:()=>{}};});
  await native.page.goto(url);await native.page.locator('#commPlus').click();
  await native.page.locator('#copyBtn').click();await native.page.locator('#exportCsvBtn').click();
  check(await native.page.evaluate(()=>nativeMessages.some(m=>m.type==='clipboard'&&m.text.includes('Коммуникации: 1'))),'native clipboard bridge receives report');
  check(await native.page.evaluate(()=>nativeMessages.some(m=>m.type==='saveFile'&&m.name.endsWith('.csv'))),'native CSV bridge receives content');
  await native.page.locator('#settingsBtn').click();await native.page.locator('#backupBtn').click();
  check(await native.page.evaluate(()=>nativeMessages.some(m=>m.type==='saveFile'&&m.name.endsWith('.json')&&JSON.parse(m.content).profiles.default.data.commCount===1)),'JSON backup preserves profile data');
  await native.context.close();
  console.log(`${checks} checks passed`);
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();server.close();});
