/* Regression checks for counters, saved profiles, pauses, undo, and offline UI. */
const assert = require('node:assert/strict');
const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require('playwright');
const html = require('../tools/bundle.cjs').bundle();
const server = http.createServer((req, res) => { res.setHeader('Content-Type', 'text/html; charset=utf-8'); res.end(html); });
let browser, checks = 0;
const check = (condition, description) => { assert(condition, description); checks++; console.log('PASS ' + description); };
const value = (page,id) => page.locator('#'+id).textContent();
const row = (page,name) => page.locator('.item-row').filter({has:page.locator('.item-name',{hasText:new RegExp('^'+name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'$')})});
async function answer(page, text, extra) {
  const dialog=page.locator('#actionDialog'); await dialog.waitFor({state:'visible'});
  if(text!==null) await dialog.locator('input:not([type=checkbox])').fill(String(text));
  if(extra) await dialog.locator('input[type=checkbox]').check();
  await dialog.locator('#dialogConfirm').click(); await dialog.waitFor({state:'hidden'});
}
async function session(url, options={}) {
  const context=await browser.newContext({viewport:{width:1100,height:950},timezoneId:'Europe/Berlin',...options});
  const errors=[],external=[];
  context.on('page',page=>page.on('pageerror',e=>errors.push(e.message)));
  await context.route('**/*',route=>{if(route.request().url().startsWith(url))return route.continue();external.push(route.request().url());return route.abort();});
  const page=await context.newPage();return {context,page,errors,external};
}
(async()=>{
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  const url='http://127.0.0.1:'+server.address().port;
  browser=await chromium.launch({headless:true,args:['--no-sandbox',...(process.env.COUNTER_TEST_SINGLE_PROCESS?['--single-process','--no-zygote','--disable-gpu']:[])],...(process.env.COUNTER_BROWSER?{executablePath:process.env.COUNTER_BROWSER}:{})});
  const {context,page,errors,external}=await session(url);
  await page.goto(url); await page.locator('.item-row').first().waitFor();
  check(await page.locator('.item-row').count()===2&&await page.locator('.item-name').allTextContents().then(n=>n.join()==='Звонки,Успешно'),'detail has only Звонки and Успешно');
  check(await page.evaluate(()=>!!document.querySelector('.side-column .shift-card + .detail-card')&&!!document.querySelector('.main-column .communications')),'communications on the left, detail under the shift on the right');
  for(let i=0;i<5;i++)await row(page,'Звонки').locator('[data-action=plus]').click();
  for(let i=0;i<2;i++)await row(page,'Успешно').locator('[data-action=plus]').click();
  for(let i=0;i<4;i++)await page.locator('#commPlus').click();
  check(await value(page,'totalComm')==='5'&&await value(page,'commCount')==='4','total equals Звонки, communications are independent');
  check(await value(page,'effSuccess')==='40%','success ratio is Успешно out of Звонки');
  await row(page,'Звонки').locator('[data-action=menu]').click();await page.locator('#itemEditBtn').click(); await answer(page,10);
  check(await value(page,'totalComm')==='10','manual category edits adjust total');
  await page.locator('#undoBtn').click();
  await row(page,'Успешно').locator('[data-action=plus]').click();
  await page.locator('#undoBtn').click(); await page.locator('#undoBtn').click();
  check(await value(page,'totalComm')==='5'&&await value(page,'commCount')==='3','undo snapshots survive subsequent mutations');
  await page.locator('#settingsBtn').click();await page.locator('#profileAddBtn').click(); await page.keyboard.press('Escape');await page.locator('#actionDialog').waitFor({state:'hidden'});
  check(await page.locator('#profileSelect option').count()===1,'cancelled new-profile dialog changes nothing');
  await page.locator('#settingsBtn').click();await page.locator('#profileAddBtn').click(); await answer(page,'Кира');
  await row(page,'Звонки').locator('[data-action=plus]').click();
  await page.locator('#settingsBtn').click();await page.locator('#profileRenameBtn').click();await answer(page,'Кира V2');
  await page.reload();
  check(await page.locator('#profileSelect').inputValue()==='Кира V2'&&await value(page,'totalComm')==='1','profile rename and selected profile persist');
  await page.locator('#profileSelect').selectOption('default');
  check(await value(page,'totalComm')==='5'&&await value(page,'commCount')==='3','profile switching restores independent data');
  const dangerous='<img src=x onerror=alert(1)>';
  await page.locator('#addBtn').click();await answer(page,dangerous);
  check(await row(page,dangerous).count()===1&&await page.locator('#itemsContainer img').count()===0,'category labels are rendered as text');
  await page.locator('#addBtn').click();await answer(page,'__proto__');
  await row(page,'__proto__').locator('[data-action=plus]').click();
  check(await row(page,'__proto__').locator('.item-count').textContent()==='1'&&await value(page,'totalComm')==='5','prototype-like category names work safely');
  await page.clock.setFixedTime(new Date('2026-10-06T07:00:00Z'));
  await page.locator('#startShiftBtn').click();
  await page.clock.setFixedTime(new Date('2026-10-06T07:30:00Z'));await page.locator('#pauseShiftBtn').click();
  await page.clock.setFixedTime(new Date('2026-10-06T07:50:00Z'));await page.reload();await page.waitForTimeout(30);
  check(await value(page,'shiftTimerValue')==='00:30:00'&&await value(page,'shiftStatusText')==='Пауза','pause remains frozen after restart');
  await page.clock.setFixedTime(new Date('2026-10-06T08:00:00Z'));await page.locator('#pauseShiftBtn').click();
  await page.clock.setFixedTime(new Date('2026-10-06T08:15:00Z'));await page.waitForTimeout(1050);
  check(await value(page,'shiftTimerValue')==='00:45:00','resumed shift excludes all paused time');
  await page.locator('#shiftNotes').fill('<b>Заметка</b>');
  await page.locator('#endShiftBtn').click();await answer(page,null);await page.locator('#historyBtn').click();
  check(await page.locator('.history-item').count()===1&&await page.locator('#historyList b').count()===0,'completed shift is archived without HTML injection');
  await page.locator('#historyCloseBtn').click();await page.locator('#historyDialog').waitFor({state:'hidden'});
  await page.locator('#resetBtn').click();await answer(page,null,true);
  check(await value(page,'totalComm')==='0'&&await value(page,'shiftStatusText')==='Не начата','reset can include shift state');
  await page.locator('#undoBtn').click();
  check(await value(page,'totalComm')==='5'&&await row(page,'__proto__').locator('.item-count').textContent()==='1'&&await value(page,'shiftStatusText')==='Завершена','reset is reversible');
  await page.clock.setFixedTime(new Date('2026-10-06T21:00:00Z'));await page.locator('#startShiftBtn').click();
  await page.locator('#shiftEnd').fill('07:00');await page.locator('#shiftEnd').blur();await page.waitForTimeout(1050);
  check(await value(page,'shiftStatusText')==='Идёт','overnight schedule does not end before midnight');
  await page.clock.setFixedTime(new Date('2026-10-07T05:00:00Z'));await page.waitForTimeout(1050);
  check(await value(page,'shiftStatusText')==='Завершена','overnight schedule ends on next day');
  check(await page.locator('html').getAttribute('data-theme')==='dark','squad dark theme is the default');
  await page.locator('#themeToggle').click();await page.reload();
  check(await page.locator('html').getAttribute('data-theme')==='light','theme selection survives restart');
  const downloadPromise=page.waitForEvent('download');await page.locator('#exportCsvBtn').click();const download=await downloadPromise;
  const stream=await download.createReadStream(),parts=[];for await(const part of stream)parts.push(part);const csv=Buffer.concat(parts).toString('utf8');
  check(csv.startsWith('\uFEFF')&&csv.includes('"__proto__";"1"'),'CSV exports UTF-8 and current values');
  // Keyboard focus is retained because counter rows are not recreated on each click.
  const plus=row(page,'Звонки').locator('[data-action=plus]');await plus.focus();await page.keyboard.press('Enter');await page.keyboard.press('Enter');
  check(await plus.evaluate(el=>document.activeElement===el),'keyboard focus survives repeated increments');
  check(errors.length===0,'no JavaScript errors');check(external.length===0,'no network resources or CDN dependencies');
  await context.close();
  if(process.env.COUNTER_TEST_SINGLE_PROCESS){await browser.close();browser=await chromium.launch({headless:true,args:['--no-sandbox','--single-process','--no-zygote','--disable-gpu'],executablePath:process.env.COUNTER_BROWSER});}
  const legacy=await session(url,{reducedMotion:'reduce',viewport:{width:390,height:844}});
  await legacy.page.addInitScript(()=>{if(!localStorage.getItem('seeded')){localStorage.setItem('seeded','1');localStorage.setItem('commStatsData',JSON.stringify({itemOrder:['НДЗ','Успешно'],counts:{НДЗ:9,Успешно:4},totalCount:13,commCount:6,shiftStart:'09:00',shiftEnd:'18:00'}));}});
  await legacy.page.goto(url);
  check(await value(legacy.page,'totalComm')==='13'&&await value(legacy.page,'commCount')==='6'&&await row(legacy.page,'Звонки').locator('.item-count').textContent()==='13'&&await row(legacy.page,'Успешно').locator('.item-count').textContent()==='4','legacy single-profile data is migrated');
  check(await legacy.page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'compact layout has no horizontal scroll');
  await legacy.page.locator('#commPlus').click();
  check(await legacy.page.locator('.ripple').count()===0,'reduced-motion preference suppresses effects');
  await legacy.context.close();
  if(process.env.COUNTER_TEST_SINGLE_PROCESS){await browser.close();browser=await chromium.launch({headless:true,args:['--no-sandbox','--single-process','--no-zygote','--disable-gpu'],executablePath:process.env.COUNTER_BROWSER});}
  const upgrade=await session(url);
  await upgrade.page.addInitScript(()=>{if(!localStorage.getItem('seeded')){localStorage.setItem('seeded','1');const old=['НДЗ','Перезвон','Успешно','Отказ','VIP','Блокировка','Сам','Трансфер'];localStorage.setItem('commProfiles',JSON.stringify({default:{itemOrder:old,items:[],history:[{date:'2026-10-07T18:00:00.000Z',total:3,comm:1,duration:1000,itemOrder:old,counts:{НДЗ:3}}]},Своя:{itemOrder:['Моя','НДЗ'],items:[],history:[]},Анна:{items:['Моя'],history:[]}}));localStorage.setItem('commStatsData_Анна',JSON.stringify({counts:{НДЗ:10,Отказ:3,Успешно:4,Моя:2}}));localStorage.setItem('commStatsData_default',JSON.stringify({counts:{НДЗ:20,Перезвон:4,Успешно:6,Отказ:5},commCount:7,status:'Пауза',startTime:'2026-10-08T06:00:00.000Z',pauseStart:'2026-10-08T07:00:00.000Z',pausedTotal:0,shiftStart:'09:00',shiftEnd:'18:00',notes:'смена'}));localStorage.setItem('commStatsData_Своя',JSON.stringify({counts:{Моя:2,НДЗ:1}}));localStorage.setItem('commLastProfile','default');}});
  await upgrade.page.goto(url);
  check(await upgrade.page.locator('.item-name').allTextContents().then(n=>n.join()==='Звонки,Успешно')&&await row(upgrade.page,'Звонки').locator('.item-count').textContent()==='35'&&await row(upgrade.page,'Успешно').locator('.item-count').textContent()==='6'&&await value(upgrade.page,'totalComm')==='35','old categories become Звонки (their sum) and Успешно');
  check(await value(upgrade.page,'shiftStatusText')==='Пауза'&&await value(upgrade.page,'shiftTimerValue')==='01:00:00'&&await value(upgrade.page,'commCount')==='7'&&await upgrade.page.locator('#shiftNotes').inputValue()==='смена','shift, timer, communications and notes survive the upgrade');
  await upgrade.page.reload();
  check(await row(upgrade.page,'Звонки').locator('.item-count').textContent()==='35','migration runs once and persists');
  await upgrade.page.locator('#profileSelect').selectOption('Своя');
  check(await upgrade.page.locator('.item-name').allTextContents().then(n=>n.join()==='Моя,НДЗ'),'custom categories are left untouched');
  await upgrade.page.locator('#profileSelect').selectOption('Анна');
  check(await upgrade.page.locator('.item-row').count()===9&&await row(upgrade.page,'НДЗ').locator('.item-count').textContent()==='10'&&await row(upgrade.page,'Моя').locator('.item-count').textContent()==='2','old-format profile with own categories keeps all counts');
  await upgrade.page.locator('#profileSelect').selectOption('default');await upgrade.page.locator('#historyBtn').click();await upgrade.page.locator('.history-item').first().click();await upgrade.page.locator('#dialogConfirm').click();
  check(await upgrade.page.locator('.item-name').allTextContents().then(n=>n.join()==='Звонки,Успешно')&&await row(upgrade.page,'Звонки').locator('.item-count').textContent()==='3','loading a pre-2.4 shift from history converts it to Звонки');
  check(upgrade.errors.length===0,'upgrade has no JavaScript errors');
  await upgrade.context.close();
  const native=await session(url);
  await native.page.addInitScript(()=>{window.chrome??={};window.chrome.webview={postMessage:m=>(window.nativeMessages??=[]).push(m),addEventListener:(type,listener)=>{if(type==='message')window.nativeListener=listener;}};});
  await native.page.goto(url);await native.page.locator('#commPlus').click();
  await native.page.locator('#copyBtn').click();await native.page.locator('#exportCsvBtn').click();
  check(await native.page.evaluate(()=>nativeMessages.some(m=>m.type==='clipboard'&&m.text.includes('Коммуникации: 1'))),'native clipboard bridge receives report');
  check(await native.page.evaluate(()=>nativeMessages.some(m=>m.type==='saveFile'&&m.name.endsWith('.csv'))),'native CSV bridge receives content');
  await native.page.locator('#settingsBtn').click();await native.page.locator('#backupBtn').click();
  check(await native.page.evaluate(()=>nativeMessages.some(m=>m.type==='saveFile'&&m.name.endsWith('.json')&&JSON.parse(m.content).profiles.default.data.commCount===1)),'JSON backup preserves profile data');
  await native.page.locator('#settingsCloseBtn').click();
  const send=data=>native.page.evaluate(d=>window.nativeListener({data:d}),data);
  check(await native.page.locator('#updateBtn').isHidden()&&!await native.page.locator('#updateDialog').evaluate(d=>d.open),'no update UI until the program reports a new version');
  await native.page.locator('#settingsBtn').click();await native.page.locator('#checkUpdateBtn').click();
  check(await native.page.evaluate(()=>nativeMessages.some(m=>m.type==='checkUpdate'))&&!await native.page.locator('#settingsDialog').evaluate(d=>d.open),'«Проверить обновления» asks the program without a restart');
  await send({type:'update',state:'latest',current:'2.4.1'});
  check((await value(native.page,'toast')).includes('последняя версия 2.4.1'),'up-to-date result is shown');
  await send({type:'update',state:'check-failed'});
  check((await value(native.page,'toast')).includes('Не удалось проверить'),'failed check is shown');
  await send({type:'update',state:'available',version:'9.9.0',current:'2.3.0'});
  check(await native.page.locator('#updateDialog').evaluate(d=>d.open)&&await value(native.page,'updateVersion')==='9.9.0'&&await value(native.page,'updateCurrent')==='2.3.0'&&await native.page.locator('#updateBtn').isVisible(),'update dialog and scarlet button appear');
  check(await native.page.evaluate(()=>document.activeElement.id)==='updateTitle','auto-opened dialog focuses its title, not «Обновить»');
  await native.page.keyboard.press('Space');
  check(await native.page.evaluate(()=>!nativeMessages.some(m=>m.type==='update')),'a stray Space does not start the update');
  await native.page.locator('#updateLaterBtn').click();
  check(!await native.page.locator('#updateDialog').evaluate(d=>d.open)&&await native.page.locator('#updateBtn').isVisible(),'«Позже» keeps the update button in the top bar');
  await native.page.locator('#updateBtn').click();await native.page.locator('#updateNowBtn').click();
  check(await native.page.evaluate(()=>nativeMessages.filter(m=>m.type==='update').length===1)&&await native.page.locator('#updateNowBtn').isDisabled()&&await native.page.locator('#updateProgress').isVisible(),'«Обновить» asks the program to download and shows progress');
  await native.page.keyboard.press('Escape');
  check(!await native.page.locator('#updateDialog').evaluate(d=>d.open)&&await value(native.page,'updateChipText')==='Скачиваем…','download dialog can be hidden, the top bar button shows the download');
  await send({type:'update',state:'progress',percent:42});
  check(await value(native.page,'updateChipText')==='Скачиваем… 42%'&&await value(native.page,'updateNowText')==='Скачиваем… 42%'&&await native.page.locator('#updateProgress').getAttribute('aria-valuenow')==='42'&&await native.page.locator('#updateProgressFill').evaluate(e=>e.style.width)==='42%','download progress is shown');
  await native.page.locator('#updateBtn').click();
  check(await native.page.locator('#updateDialog').evaluate(d=>d.open)&&await native.page.locator('#updateNowBtn').isDisabled()&&await native.page.locator('#updateProgress').isVisible(),'reopened dialog shows the running download');
  await send({type:'update',state:'error',message:'Нет доступа к папке'});
  check(await native.page.locator('#updateNowBtn').isEnabled()&&await value(native.page,'updateNowText')==='Повторить'&&(await value(native.page,'updateMessage')).startsWith('Нет доступа к папке')&&await native.page.locator('#updateProgress').isHidden(),'download error offers retry');
  await native.page.locator('#updateManualBtn').click();
  check(await native.page.evaluate(()=>nativeMessages.some(m=>m.type==='openReleases')),'manual download opens the releases page');
  await native.page.locator('#updateNowBtn').click();
  check(await native.page.evaluate(()=>nativeMessages.filter(m=>m.type==='update').length===2),'retry requests the download again');
  check(await value(native.page,'updateChipText')==='Скачиваем…','retry shows the download on the top bar button');
  check(native.errors.length===0,'update flow has no JavaScript errors');
  await native.context.close();
  console.log(`${checks} checks passed`);
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();server.close();});
